# Generated by Django 5.1.4 on 2025-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
