# Generated by Django 5.1.4 on 2024-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_profile_city_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
