# Generated by Django 5.1.4 on 2024-12-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_product_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
