# Generated by Django 5.1.4 on 2025-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_servicecategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
